package gui;

import modelo.Jogo;

public class Panel_Inicio extends javax.swing.JPanel {

    public Panel_Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dicaTxt = new javax.swing.JTextField();
        palavraSegredoTxt = new javax.swing.JTextField();
        dicaLabel = new javax.swing.JLabel();
        palavraSegredoLabel = new javax.swing.JLabel();
        iniciaBnt = new javax.swing.JButton();
        jogado1Label = new javax.swing.JLabel();
        jogoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(255, 255, 204));

        dicaTxt.setBackground(new java.awt.Color(255, 255, 204));
        dicaTxt.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        dicaTxt.setForeground(new java.awt.Color(0, 0, 0));
        dicaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dicaTxtActionPerformed(evt);
            }
        });

        palavraSegredoTxt.setBackground(new java.awt.Color(255, 255, 204));
        palavraSegredoTxt.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        palavraSegredoTxt.setForeground(new java.awt.Color(0, 0, 0));
        palavraSegredoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palavraSegredoTxtActionPerformed(evt);
            }
        });

        dicaLabel.setBackground(new java.awt.Color(255, 204, 204));
        dicaLabel.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        dicaLabel.setForeground(new java.awt.Color(0, 0, 0));
        dicaLabel.setText("Informe a dica:");

        palavraSegredoLabel.setBackground(new java.awt.Color(255, 204, 204));
        palavraSegredoLabel.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        palavraSegredoLabel.setForeground(new java.awt.Color(0, 0, 0));
        palavraSegredoLabel.setText("Informe a palavra:");

        iniciaBnt.setBackground(new java.awt.Color(204, 204, 255));
        iniciaBnt.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        iniciaBnt.setForeground(new java.awt.Color(0, 0, 0));
        iniciaBnt.setText("INICIAR JOGO");
        iniciaBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciaBntActionPerformed(evt);
            }
        });

        jogado1Label.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jogado1Label.setForeground(new java.awt.Color(0, 0, 0));
        jogado1Label.setText("Jogador 1");

        jogoLabel.setFont(new java.awt.Font("SimSun-ExtB", 1, 48)); // NOI18N
        jogoLabel.setForeground(new java.awt.Color(204, 204, 255));
        jogoLabel.setText("JOGO DA FORCA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jogado1Label)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(palavraSegredoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dicaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(palavraSegredoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(iniciaBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jogoLabel)))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jogoLabel)
                .addGap(103, 103, 103)
                .addComponent(jogado1Label)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(palavraSegredoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palavraSegredoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170)
                        .addComponent(iniciaBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dicaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(261, 261, 261))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dicaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dicaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dicaTxtActionPerformed

    private void palavraSegredoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palavraSegredoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palavraSegredoTxtActionPerformed

    private void iniciaBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaBntActionPerformed
        //botão de iniciar
        String palavra = palavraSegredoLabel.getText();
        String dica = dicaLabel.getText();

        Jogo novoJogo = new Jogo(palavra, dica);

        //mudar de painel
    }//GEN-LAST:event_iniciaBntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dicaLabel;
    private javax.swing.JTextField dicaTxt;
    private javax.swing.JButton iniciaBnt;
    private javax.swing.JLabel jogado1Label;
    private javax.swing.JLabel jogoLabel;
    private javax.swing.JLabel palavraSegredoLabel;
    private javax.swing.JTextField palavraSegredoTxt;
    // End of variables declaration//GEN-END:variables
}
