package gui;

public class Panel_Jogo extends javax.swing.JPanel {

    public Panel_Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogador2_Painel = new javax.swing.JPanel();
        letraTxt = new javax.swing.JTextField();
        dicaLabel = new javax.swing.JLabel();
        forcaPainel = new javax.swing.JPanel();
        errosLabel = new javax.swing.JLabel();
        tentativaLabel = new javax.swing.JLabel();
        rodadaLabel = new javax.swing.JLabel();
        jogado2Label = new javax.swing.JLabel();
        jogoLabel = new javax.swing.JLabel();
        rodadaLabel1 = new javax.swing.JLabel();
        dicaTxt2 = new javax.swing.JLabel();
        tenatativasTxt2 = new javax.swing.JLabel();
        errosTxt2 = new javax.swing.JLabel();
        rodadaTxt2 = new javax.swing.JLabel();
        verificaBnt = new javax.swing.JButton();

        jogador2_Painel.setBackground(new java.awt.Color(255, 255, 204));

        letraTxt.setBackground(new java.awt.Color(255, 255, 204));
        letraTxt.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        letraTxt.setForeground(new java.awt.Color(0, 0, 0));

        dicaLabel.setBackground(new java.awt.Color(255, 204, 204));
        dicaLabel.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        dicaLabel.setForeground(new java.awt.Color(0, 0, 0));
        dicaLabel.setText("Dica:");

        forcaPainel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout forcaPainelLayout = new javax.swing.GroupLayout(forcaPainel);
        forcaPainel.setLayout(forcaPainelLayout);
        forcaPainelLayout.setHorizontalGroup(
            forcaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        forcaPainelLayout.setVerticalGroup(
            forcaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        errosLabel.setBackground(new java.awt.Color(255, 204, 204));
        errosLabel.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        errosLabel.setForeground(new java.awt.Color(0, 0, 0));
        errosLabel.setText("Erros:");

        tentativaLabel.setBackground(new java.awt.Color(255, 204, 204));
        tentativaLabel.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        tentativaLabel.setForeground(new java.awt.Color(0, 0, 0));
        tentativaLabel.setText("Tentativa:");

        rodadaLabel.setBackground(new java.awt.Color(255, 204, 204));
        rodadaLabel.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        rodadaLabel.setForeground(new java.awt.Color(0, 0, 0));
        rodadaLabel.setText("Letra:");

        jogado2Label.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jogado2Label.setForeground(new java.awt.Color(0, 0, 0));
        jogado2Label.setText("Jogador 2");

        jogoLabel.setFont(new java.awt.Font("SimSun-ExtB", 1, 48)); // NOI18N
        jogoLabel.setForeground(new java.awt.Color(204, 204, 255));
        jogoLabel.setText("JOGO DA FORCA");

        rodadaLabel1.setBackground(new java.awt.Color(255, 204, 204));
        rodadaLabel1.setFont(new java.awt.Font("SimSun", 2, 18)); // NOI18N
        rodadaLabel1.setForeground(new java.awt.Color(0, 0, 0));
        rodadaLabel1.setText("Rodada:");

        dicaTxt2.setText("jLabel1");

        tenatativasTxt2.setText("jLabel1");

        errosTxt2.setText("jLabel1");

        rodadaTxt2.setText("jLabel1");

        verificaBnt.setBackground(new java.awt.Color(204, 204, 255));
        verificaBnt.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        verificaBnt.setForeground(new java.awt.Color(0, 0, 0));
        verificaBnt.setText("VERIFICA");
        verificaBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaBntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jogador2_PainelLayout = new javax.swing.GroupLayout(jogador2_Painel);
        jogador2_Painel.setLayout(jogador2_PainelLayout);
        jogador2_PainelLayout.setHorizontalGroup(
            jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogador2_PainelLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jogoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jogador2_PainelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jogado2Label)
                    .addComponent(dicaTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jogador2_PainelLayout.createSequentialGroup()
                        .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tentativaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenatativasTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errosTxt2)))
                    .addGroup(jogador2_PainelLayout.createSequentialGroup()
                        .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rodadaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rodadaTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jogador2_PainelLayout.createSequentialGroup()
                                .addComponent(rodadaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(verificaBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(forcaPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jogador2_PainelLayout.setVerticalGroup(
            jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogador2_PainelLayout.createSequentialGroup()
                .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jogador2_PainelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jogoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forcaPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jogador2_PainelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jogado2Label)
                        .addGap(43, 43, 43)
                        .addComponent(dicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dicaTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tentativaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenatativasTxt2))
                        .addGap(7, 7, 7)
                        .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(errosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errosTxt2))
                        .addGap(37, 37, 37)
                        .addComponent(rodadaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jogador2_PainelLayout.createSequentialGroup()
                                .addGroup(jogador2_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rodadaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(verificaBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rodadaTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jogador2_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jogador2_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verificaBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificaBntActionPerformed
        
    }//GEN-LAST:event_verificaBntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dicaLabel;
    private javax.swing.JLabel dicaTxt2;
    private javax.swing.JLabel errosLabel;
    private javax.swing.JLabel errosTxt2;
    private javax.swing.JPanel forcaPainel;
    private javax.swing.JLabel jogado2Label;
    private javax.swing.JPanel jogador2_Painel;
    private javax.swing.JLabel jogoLabel;
    private javax.swing.JTextField letraTxt;
    private javax.swing.JLabel rodadaLabel;
    private javax.swing.JLabel rodadaLabel1;
    private javax.swing.JLabel rodadaTxt2;
    private javax.swing.JLabel tenatativasTxt2;
    private javax.swing.JLabel tentativaLabel;
    private javax.swing.JButton verificaBnt;
    // End of variables declaration//GEN-END:variables
}
